server:
  port: ${PORT:8888}

spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/rolandojr/config-server-repo.git
  application:
    name: spring-boot-config-server

eureka:
  client:
    service-url:
      defaultZone: http://${HOSTNAME_EUREKA:localhost:8761}/eureka